In [1]:
import os
import math
import re
import numpy as np
import pandas as pd
import pdfplumber
import tabula
import PyPDF2
import warnings
warnings.filterwarnings("ignore")

In [2]:
pdf_path = "/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2013.pdf"

## `pdfplumber`

In [3]:
table_settings = {
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines"
}

pdf = pdfplumber.open(pdf_path)

table = pdf.pages[3].extract_tables(table_settings)
pd.DataFrame(table[0])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Period,Visitors Arrivals,None,None,None,Returning Residents,None,None,None,Total Arrivals,None,None,None,Total Departures,None,None,None,Net\nMigration
1,None,Air,Ship,Yacht,Total,Air,Ship,Yacht,Total,Air,Ship,Yacht,Total,Air,Ship,Yacht,Total,None
2,2005\n2006\n2007\n2008\n2009\n2010\n2011\n2012...,"42,437 11,840 943 55,220\n46,268 10,809 868 57...",None,None,None,"21,066 21,066\n20,707 20,707\n22,313 22,313\n2...",None,None,None,"63,503 11,840 943 76,286\n66,975 10,809 868 78...",None,None,None,"60,276 11,871 1,393 73,540\n68,637 13,049 582 ...",None,None,None,"2,746\n(3,616)\n(7,829)\n(1,762)\n443\n(1,101)..."
3,2010,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,January\nFebruary\nMarch\nApril\nMay\nJune\nJu...,"3,158 646 4 3,808\n2,379 - 5 2,384\n3,134 853 ...",None,None,None,"3,019 3,019\n2,083 2,083\n1,730 1,730\n1,906 1...",None,None,None,"6,177 646 4 6,827\n4,462 - 5 4,467\n4,864 853 ...",None,None,None,"7,822 642 - 8,464\n5,096 - 1 5,097\n4,993 850 ...",None,None,None,"(1,637)\n(630)\n(128)\n(385)\n1,042\n1,347\n(8..."
5,2011,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
6,January\nFebruary\nMarch\nApril\nMay\nJune\nJu...,"2,844 2 2,846\n2,302 6,847 14 9,163\n2,477 1,4...",None,None,None,"3,185 3,185\n1,985 1,985\n1,947 1,947\n2,152 2...",None,None,None,"6,029 - 2 6,031\n4,287 6,847 14 11,148\n4,424 ...",None,None,None,"7,755 - - 7,755\n6,031 6,859 5 12,895\n4,526 1...",None,None,None,"(1,724)\n(1,747)\n(108)\n320\n996\n1,044\n(132..."
7,2012,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
8,January\nFebruary\nMarch\nApril\nMay\nJune\nJu...,"3,043 - - 3,043\n2,241 1,220 4 3,465\n2,629 86...",None,None,None,"3,018 3,018\n1,913 1,913\n1,927 1,927\n1,847 1...",None,None,None,"6,061 - - 6,061\n4,154 1,220 4 5,378\n4,556 86...",None,None,None,"8,296 - - 8,296\n5,637 1,365 3 7,005\n4,866 81...",None,None,None,"(2,235)\n(1,627)\n(256)\n(113)\n892\n1,897\n33..."
9,2013,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
10,January\nFebruary\nMarch\nApril\nMay\nJune\nJu...,"2,927 922 9 3,858\n2,621 1,310 2 3,933\n2,797 ...",None,None,None,"3,085 3,085\n1,816 1,816\n1,880 1,880\n2,096 2...",None,None,None,"6,012 922 9 6,943\n4,437 1,310 2 5,749\n4,677 ...",None,None,None,"7,440 922 8 8,370\n6,077 1,310 - 7,387\n5,035 ...",None,None,None,"(1,427)\n(1,638)\n(357)\n121\n1,086\n1,317\n(8..."
11,2014,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
12,January\nFebruary\nMarch\nApril\nMay\nJune\nJu...,"3,259 1,446 3 4,708\n2,441 3,677 24 6,142\n2,4...",None,None,None,"3,167 3,167\n1,861 1,861\n1,880 1,880\n2,034 2...",None,None,None,"6,426 1,446 3 7,875\n4,302 3,677 24 8,003\n4,3...",None,None,None,"8,028 1,444 - 9,472\n5,958 3,676 14 9,648\n4,8...",None,None,None,"(1,597)\n(1,645)\n(527)\n348\n982\n944\n(661)\..."
13,2015,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
14,"January 3,343 2,935 20 6,298 3,720 3,720 7,063...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

## `tablua-py`

In [3]:
tonga_lsts = os.listdir("data/tonga")
filepaths = [os.getcwd() + "/data/tonga/" +
             path for path in tonga_lsts if "Dec" in path]

for file in filepaths:
    print(file)

/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-Report-Dec-2017.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-December-Report-2019.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2014.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2015.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-December-Report-2020.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2013.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/12-Migration-Report-Dec-2016.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-2012.pdf

In [43]:
def locate_table(filepath: str,
                 search_string: str,
                 ignore_case=False):

    search_lst = list()
    reader = PyPDF2.PdfReader(filepath)

    for page_num, page in enumerate(reader.pages):
        try:
            page_text = page.extract_text()
            hits = None
            if ignore_case == False:
                hits = re.search(search_string, page_text.lower())
            else:
                hits = re.search(
                    search_string, page_text.lower(), re.IGNORECASE)

            if hits:
                search_lst.append(page_num+1)
        except:
            pass
    return {"table_loc": search_lst}


def load_pdf(filepath: str,
             search_string: str,
             table_num: int):

    table_loc = locate_table(filepath, search_string,
                             ignore_case=True)["table_loc"]
    if len(table_loc) != 0:
        table_num = table_loc[-1]
        dfs = tabula.read_pdf(filepath, pages=table_num, stream=True)
        df = dfs[0]
        df.columns = df.iloc[0, :].to_list()

    else:
        dfs = tabula.read_pdf(filepath, pages="all", stream=True)
        df = dfs[table_num]
        df.columns = df.iloc[0, :].to_list()

    return df


def split_time(df: pd.DataFrame,
               time_var: str):

    year_idx, month_idx = list(), list()
    for idx in df.index:
        if (str(df[time_var][idx]).isdigit() == True):
            year_idx.append(idx)
        else:
            month_idx.append(idx)

    latest_year_idx = max(year_idx)

    return latest_year_idx, year_idx, month_idx


def remove_separator(df: pd.DataFrame):

    colnames = df.columns
    for col in colnames:
        col_series = pd.Series(df[col].values.flatten())
        df[col] = (df[col].str.replace(",", "")
                              .replace("-", "0")
                              .replace("(", "")
                              .replace(")", ""))

    return df


def separate_data(df: pd.DataFrame,
                  var: str):

    air_number, ship_number = list(), list()
    for i in df[var]:
        try:
            air, ship = i.split(" ")[0], i.split(" ")[-1]
            air_number.append(air)
            ship_number.append(ship)
        except:
            if type(i) != float:
                length = len(i.split(" "))
                if length < 2:
                    air_number.append(i.split(" ")[0])
                    ship_number.append(0)
            else:
                pass

    df["Air"], df["Ship"] = air_number, ship_number
    df = df.drop(var, axis=1)
    return df


def check_quality(df: pd.DataFrame,
                  exclude_vars: list):

    new_df = df.iloc[:, ~df.columns.isin(exclude_vars)]
    checked_vars = new_df.columns[~new_df.columns.isin(["Total"])].to_list()

    for idx in new_df.index:
        row_sum = 0
        for var in checked_vars:
            row_sum += int(new_df[var][idx])
        if int(new_df["Total"][idx]) == row_sum:
            pass
        else:
            return False

In [ ]:
years = pd.DataFrame()
for file in filepaths[:-1]:
    print(file)
    df = load_pdf(file, "Monthly Arrival and Departure", table_num=-5)
    latest_year, year_idx, month_idx = split_time(df, "Period")
    month, year = df.iloc[month_idx, 0:4], df.iloc[year_idx, 0:4]
    year = remove_separator(year)
    year = separate_data(year, "Air Ship")
    if check_quality(year, ["Period"]) == False:
        print(file, "went wrong!")
    else:
        years = pd.concat([years, year], axis=0)

/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-Report-Dec-2017.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-Report-Dec-2017.pdf went wrong!
/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-December-Report-2019.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-December-Report-2019.pdf went wrong!
/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2014.pdf

Got stderr: Nov 02, 2022 4:21:57 PM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: inherited resources of source document are not imported to destination page
Nov 02, 2022 4:21:57 PM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: call importedPage.setResources(page.getResources()) to do this

/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2015.pdf

Got stderr: Nov 02, 2022 4:22:04 PM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: inherited resources of source document are not imported to destination page
Nov 02, 2022 4:22:04 PM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: call importedPage.setResources(page.getResources()) to do this

/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-December-Report-2020.pdf
/Users/czhang/Desktop/PO-Tourism/data/tonga/Migration-December-Report-2020.pdf went wrong!
/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2013.pdf

In [ ]:
year

In [48]:
year

  Period Air Ship Yacht   NaN  Total
1   2005    42437 11840   943  55220
2   2006    46268 10809   868  57945
3   2007     43344 8790  1140  53274
4   2008    50462 14599  1828  66889
5   2009    45711 27641  1317  74669
6   2010    47081 16265  1659  65005
7   2011    46005 20519   989  67513
8   2012     47352 7957  1816  57125

In [194]:
test = load_pdf("/Users/czhang/Desktop/PO-Tourism/data/tonga/12-December-Migration-Report-2013.pdf", "4-", -5)
#latest_year, year_idx, month_idx = split_time(test, "Period")
#month, year = test.iloc[month_idx, 0:4], test.iloc[year_idx, 0:4]

Got stderr: Nov 02, 2022 3:10:13 PM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: inherited resources of source document are not imported to destination page
Nov 02, 2022 3:10:13 PM org.apache.pdfbox.pdmodel.PDDocument importPage
WARNING: call importedPage.setResources(page.getResources()) to do this

IndexError: list index out of range

In [102]:
check_quality(year, ["Period"])

In [23]:
month = (remove_separator(month).iloc[1:, ]
         .dropna(how="all")
         .reset_index()
         .drop("index", axis=1))

month = separate_data(month, "Air Ship")
month

       Period Yacht Total   Air  Ship
0     January     4  3808  3158   646
1    February     5  2384  2379     0
2       March     5  3992  3134   853
3       April    30  5650  2818  2802
4         May   177  9150  3670  5303
..        ...   ...   ...   ...   ...
67     August   231  5040  4809     0
68  September   282  7150  4915  1953
69    October   203  7708  4045  3460
70   November    96  3937  3550   291
71   December     0  8544  8444   100

[72 rows x 5 columns]

## `pdfminer`

In [5]:
from io import StringIO

from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser

In [6]:
output_string = StringIO()
with open(pdf_path, 'rb') as in_file:
    parser = PDFParser(in_file)
    doc = PDFDocument(parser)
    rsrcmgr = PDFResourceManager()
    device = TextConverter(rsrcmgr, output_string, laparams=LAParams())
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.create_pages(doc):
        interpreter.process_page(page)

In [7]:
output_string.getvalue()

"INTERNATIONAL ARRIVALS AND DEPARTURES\nINTERNATIONAL ARRIVALS AND DEPARTURES\nINTERNATIONAL ARRIVALS AND DEPARTURES\nJanuary 2014\nJanuary 2014\nJanuary 2014\n\nGovernment of Tonga\nGovernment of Tonga\nGovernment of Tonga\n\nSD18M-07\nSD18M-07\nSD18M-07\n\nStatistical Bulletin\nStatistical Bulletin\nStatistical Bulletin\n\nMonth of\nMonth of\n\nChange from\nChange from\n\nChange from\nChange from\n\n January 2014\n January 2014\n\nNumber\nNumber\n\nprevious month\nprevious month\n\nprevious year\nprevious year\n\nAll Arrivals\nAll Arrivals\nAir Visitors\nAir Visitors\nAir Returning Residents\nAir Returning Residents\nCruise Ships\nCruise Ships\nYachts\nYachts\nAll Departures\nAll Departures\n\n7,875\n7,875\n3,259\n3,259\n3,167\n3,167\n1,446\n1,446\n3\n3\n9,472\n9,472\n\n-7.2\n-7.2\n-49.3\n-49.3\n54.6\n54.6\n0.0\n0.0\n-76.9\n-76.9\n30.7\n30.7\n\n13.4\n13.4\n11.3\n11.3\n2.7\n2.7\n56.8\n56.8\n-66.7\n-66.7\n13.2\n13.2\n\nFig. 1:  January Air Arrivals and Departures 2003 - 2013\nFig. 1:  January Air Arrivals and Departures 2003 - 2013\n\n10000\n10000\n\n9000\n9000\n\n8000\n8000\n\n7000\n7000\n\n6000\n6000\n\n5000\n5000\n\n4000\n4000\n\n3000\n3000\n\n2000\n2000\n\n1000\n1000\n\n0\n0\n\n9000\n9000\n\n8000\n8000\n\n7000\n7000\n\n6000\n6000\n\n5000\n5000\n\n4000\n4000\n\n3000\n3000\n\n2000\n2000\n\n1000\n1000\n\n0\n0\n\n2003\n2003\n\n2004\n2004\n\n2005\n2005\n\n2006\n2006\n\n2007\n2007\n\n2008\n2008\n\n2009\n2009\n\n2010\n2010\n\n2011\n2011\n\n2012\n2012\n\n2013\n2013\n\n2013\n2013\n\nArrivals\nArrivals\n\nDepartures\nDepartures\n\nFig 2.  Monthly Air Arrivals vs the corresponding month of the previous year.\nFig 2.  Monthly Air Arrivals vs the corresponding month of the previous year.\n\nA decline of 7.2% of all arrivals (7,875)\nA decline of 7.2% of all arrivals (7,875)\nA decline of 7.2% of all arrivals (7,875)\ncompared to the previous month of\ncompared to the previous month of\ncompared to the previous month of\nDecember 2013 (8,490)\nDecember 2013 (8,490)\nDecember 2013 (8,490)\nA decline of 49.3% of all air visitors\nA decline of 49.3% of all air visitors\nA decline of 49.3% of all air visitors\n(3,259) compared to December 2013\n(3,259) compared to December 2013\n(3,259) compared to December 2013\n(6,429)\n(6,429)\n(6,429)\nAn increase of 54.6% (3,167) of\nAn increase of 54.6% (3,167) of\nAn increase of 54.6% (3,167) of\nreturning residents compared to previous\nreturning residents compared to previous\nreturning residents compared to previous\nmonth (2,048)\nmonth (2,048)\nmonth (2,048)\nThere were 1,446 passengers arrived by\nThere were 1,446 passengers arrived by\nThere were 1,446 passengers arrived by\ncruise ship, for January 2014.\ncruise ship, for January 2014.\ncruise ship, for January 2014.\nA decline of 76.9% of yacht arrivals\nA decline of 76.9% of yacht arrivals\nA decline of 76.9% of yacht arrivals\ncompared to the  previous month\ncompared to the  previous month\ncompared to the  previous month\nAn increase of 30.7% of all departures\nAn increase of 30.7% of all departures\nAn increase of 30.7% of all departures\nfrom December 2013.\nfrom December 2013.\nfrom December 2013.\n\nTotal air arrivals in January 2014 were\nTotal air arrivals in January 2014 were\nTotal air arrivals in January 2014 were\n6,426 an  increase of 6.9% compared to\n6,426 an  increase of 6.9% compared to\n6,426 an  increase of 6.9% compared to\nJanuary 2013 (6,012).\nJanuary 2013 (6,012).\nJanuary 2013 (6,012).\n\nTotal air departures of 8,028  in January\nTotal air departures of 8,028  in January\nTotal air departures of 8,028  in January\n2014, an increase of 7.9% compared to\n2014, an increase of 7.9% compared to\n2014, an increase of 7.9% compared to\nJanuary  2013  (7,440)\nJanuary  2013  (7,440)\nJanuary  2013  (7,440)\n\nTotal air visitor arrivals in January  2014\nTotal air visitor arrivals in January  2014\nTotal air visitor arrivals in January  2014\nwere 3,259 an  increase of  11.3%\nwere 3,259 an  increase of  11.3%\nwere 3,259 an  increase of  11.3%\ncompared to  January 2013  (2,927)\ncompared to  January 2013  (2,927)\ncompared to  January 2013  (2,927)\n\nFeb\nFeb\n\nMar\nMar\n\nApr\nApr\n\nMay\nMay\n\nJun\nJun\n\nJul\nJul\n\nAug\nAug\n\nSep\nSep\n\nOct\nOct\n\nNov\nNov\n\nDec\nDec\n\nJan\nJan\n\nFeb 2012 - Jan 2013\nFeb 2012 - Jan 2013\n\nFeb 2013 - Jan 2014\nFeb 2013 - Jan 2014\n\nIssued by:  Statistics Department, P.O. Box 149, Nuku’alofa, Kingdom of Tonga.     Telephone: (676) 23-300/23-913 Fax: (676)24 303\nIssued by:  Statistics Department, P.O. Box 149, Nuku’alofa, Kingdom of Tonga.     Telephone: (676) 23-300/23-913 Fax: (676)24 303\nIssued by:  Statistics Department, P.O. Box 149, Nuku’alofa, Kingdom of Tonga.     Telephone: (676) 23-300/23-913 Fax: (676)24 303\n\nwww.spc.int/prism/tonga/\nwww.spc.int/prism/tonga/\nwww.spc.int/prism/tonga/\n\nPage 1\nPage 1\nPage 1\n\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\x0cFig. 3:  Air Visitors by Purpose of Visit January, 2014\n\nNot Stated\n\nBusiness/Conference\n\nOther Reasons\n\nHoliday/Vacation\n\nVisiting Relatives/Friends\n\n0\n\n5\n\n10\n\n15\n\n20\n\n25\n\n30\n\n35\n\n40\n\n45\n\n50\n\nFig. 4:  Air visitors by Country of Usual Residence January, 2014\n\nOther European\nCountries\n6%\n\nOther Asian\nCountries\n5%\n\nOther Pacific Islands\n6%\n\nAmerica\n7%\n\nOthers\n1%\n\nAustralia\n22%\n\nNew Zealand\n53%\n\nVisiting Relatives/Friends  made up\n46.7% (1,522) of all air visitors to the\nKingdom in the month of  January.\n\n29.7% (969) of the total visitors were\nhere on Holiday/Vacation.\n\nVisitors who were here on Business or\nConference made up 8.9% (289) and\nthose with other reasons were 10.7%\n(350)\n\nNew Zealand remains as the leading country\nin visitors arrivals by country of usual\nresidence, accounting for 52.8% (1,720) of\ntotal air visitors\n\nThis was followed by Australia with 21.9 %\n(713), and  USA 7.4% (240)\n\nFig. 5:  Air Departures by Country of Usual Residence January, 2013\n\nOthers\n9%\n\nAustralia\n17%\n\n\uf0b7 Most of the persons departing in the\nmonth of January were residents of\nTonga (3,506) followed by New Zealand\n(1,902) and Australia (1,393)\n\nTonga\n44%\n\nNew Zealand\n24%\n\nAmerica\n6%\n\nIssued by:  Statistics Department, P.O. Box 149, Nuku’alofa, Kingdom of Tonga.     Telephone: (676) 23-300/23-913 Fax: (676)24 303\n\nwww.spc.int/prism/tonga/\n\nPage 2\n\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\uf0b7\n\x0cBackground Information\n\nData is extracted from the arrival and departure cards of the Immigration Department, Ministry of Foreign Affairs\nand  Customs vessel  &  yacht  log  book.  The Statistics Department reconciles  the  figures  from  the  Air  Terminal\nServices Manifest, Tonga Airport Limited and Ports Authority Manifest to produce final published data.\n\nStatistics  on  Overseas  Arrivals  and  Departures  related  to the  number  of  movements  of  travelers  rather  than  the\nnumber  of  travelers  (i.e.  the  multiple  movements  of  individual  persons  during  a  given  reference  period  are  all\ncounted).\n\nDefinitions\n\n\uf07d A Visitor\n\nis a person other than a Tongan citizen, permit holder and exempted person, who usually stay\nat least 24 hours in the  Kingdom, or who stays  overnight in accommodation within Tonga. This  refers to\npassengers arriving by air and yacht only.\n\n\uf07d Cruise Ship Passengers\n\nare defined  as those  who arrive and depart in the same vessel which is  on a\ncruise  trip,  and  use  that  vessel’s  accommodation  during  their  stay  in  Tonga.  They  are  also  known  as\n“Excursionist”\n\n\uf07d A Returning resident\n\nis  a person  who  has  the  Kingdom  of  Tonga  as  their  permanent  address  for\nmore than six months of the year and returns to Tonga after a trip overseas. Tongan residence is self-defined\nas reported by travelers when completing the Passenger Arrival Card.\n\n\uf07d Mode of Transport Only  air,  yacht  and  cruise  ships  passengers  are  included.  Passenger/crew  on  cargo,\n\nnavy or special vessels are excluded.\n\nThe  Statistics  Department  wishes  to  acknowledge  the  cooperation  of  the  Immigration  Department  of  the\nMinistry  of  Foreign  Affairs  and  Trade  and  the  Custom  Department  of  the  Ministry  of  Revenue  Services,  Air\nTerminal Services, Ports Authority making it possible to publish these important statistics.\n\nIssued by:  Statistics Department, P.O. Box 149, Nuku’alofa, Kingdom of Tonga.     Telephone: (676) 23-300/23-913 Fax: (676)24 303\n\nwww.spc.int/prism/tonga/\n\nPage 3\n\n\x0cTable 1.  Monthly Arrival and Departure by Mode of Travel and Net Migration, 2010  -  2014\n\nVisitors Arrivals\n\nReturning Residents\n\nTotal Arrivals\n\nTotal Departures\n\nNet\n\nPeriod\n\nAir\n\nShip\n\nYacht\n\nTotal\n\nAir\n\nShip Yacht Total\n\nAir\n\nShip\n\nYacht\n\nTotal\n\nAir\n\nShip\n\nYacht\n\nTotal\n\nMigration\n\n2005\n\n2006\n\n2007\n\n2008\n\n2009\n\n2010\n\n2011\n\n2012\n\n2013\n\nJanuary\n\nFebruary\n\nMarch\n\nApril\n\nMay\n\nJune\n\nJuly\n\nAugust\n\nSeptember\n\nOctober\n\nNovember\n\nDecember\n\nJanuary\n\nFebruary\n\nMarch\n\nApril\n\nMay\n\nJune\n\nJuly\n\nAugust\n\nSeptember\n\nOctober\n\nNovember\n\nDecember\n\nJanuary\n\nFebruary\n\nMarch\n\nApril\n\nMay\n\nJune\n\nJuly\n\nAugust\n\nSeptember\n\nOctober\n\nNovember\n\nDecember\n\nJanuary\n\nFebruary\n\nMarch\n\nApril\n\nMay\n\nJune\n\nJuly\n\nAugust\n\nSeptember\n\nOctober\n\nNovember\n\nDecember\n\n42,437\n\n11,840\n\n46,268\n\n10,809\n\n943\n\n868\n\n55,220\n\n21,066\n\n57,945\n\n20,707\n\n43,344\n\n8,790\n\n1,140\n\n53,274\n\n22,313\n\n50,462\n\n14,599\n\n1,828\n\n66,889\n\n24,239\n\n45,711\n\n27,641\n\n47,081\n\n16,265\n\n1,317\n\n1,659\n\n74,669\n\n25,134\n\n65,005\n\n24,501\n\n46,005\n\n20,519\n\n1,849\n\n68,373\n\n26,587\n\n47,457\n\n48,188\n\n7,957\n\n9,432\n\n1,816\n\n2,045\n\n57,230\n\n25,170\n\n59,665\n\n25,808\n\n3,158\n\n2,379\n\n3,134\n\n2,818\n\n3,670\n\n4,701\n\n4,900\n\n4,216\n\n4,576\n\n3,467\n\n3,569\n\n6,493\n\n2,844\n\n2,302\n\n2,477\n\n3,520\n\n3,812\n\n4,323\n\n5,280\n\n4,486\n\n3,561\n\n3,155\n\n2,996\n\n7,249\n\n3,043\n\n2,241\n\n2,629\n\n3,022\n\n3,497\n\n4,892\n\n5,789\n\n4,286\n\n4,156\n\n3,909\n\n4,052\n\n5,941\n\n2,927\n\n2,621\n\n2,797\n\n3,088\n\n3,965\n\n4,693\n\n5,415\n\n4,753\n\n4,068\n\n4,037\n\n3,395\n\n6,429\n\n646\n\n-\n\n853\n\n2,802\n\n5,303\n\n-\n\n-\n\n-\n\n5,275\n\n-\n\n1,386\n\n-\n\n6,847\n\n1,407\n\n3,038\n\n-\n\n-\n\n2,376\n\n-\n\n-\n\n4,387\n\n-\n\n2,464\n\n-\n\n1,220\n\n865\n\n3,063\n\n-\n\n-\n\n-\n\n-\n\n-\n\n1,817\n\n618\n\n374\n\n922\n\n1,310\n\n626\n\n3,205\n\n-\n\n700\n\n-\n\n-\n\n1,954\n\n-\n\n715\n\n-\n\n4\n\n5\n\n5\n\n30\n\n177\n\n275\n\n238\n\n246\n\n188\n\n352\n\n126\n\n13\n\n2\n\n14\n\n16\n\n37\n\n250\n\n242\n\n239\n\n419\n\n242\n\n257\n\n112\n\n19\n\n-\n\n4\n\n15\n\n44\n\n302\n\n182\n\n235\n\n254\n\n351\n\n315\n\n86\n\n28\n\n9\n\n2\n\n11\n\n50\n\n328\n\n182\n\n282\n\n305\n\n339\n\n403\n\n121\n\n13\n\n3,808\n\n3,019\n\n2,384\n\n3,992\n\n5,650\n\n9,150\n\n4,976\n\n5,138\n\n4,462\n\n10,039\n\n3,819\n\n5,081\n\n6,506\n\n2,846\n\n9,163\n\n3,900\n\n6,595\n\n4,062\n\n4,565\n\n7,895\n\n4,905\n\n3,803\n\n7,799\n\n3,108\n\n9,732\n\n3,043\n\n3,465\n\n3,509\n\n6,129\n\n3,799\n\n5,074\n\n6,024\n\n4,540\n\n4,507\n\n6,041\n\n4,756\n\n6,343\n\n3,858\n\n3,933\n\n3,434\n\n6,343\n\n4,293\n\n5,575\n\n5,697\n\n5,058\n\n6,361\n\n4,440\n\n4,231\n\n6,442\n\n2,083\n\n1,730\n\n1,906\n\n2,230\n\n1,888\n\n1,814\n\n1,848\n\n1,756\n\n1,809\n\n2,378\n\n2,040\n\n3,185\n\n1,985\n\n1,947\n\n2,152\n\n2,588\n\n1,913\n\n1,998\n\n1,889\n\n2,063\n\n2,164\n\n2,354\n\n2,349\n\n3,018\n\n1,913\n\n1,927\n\n1,847\n\n2,486\n\n1,836\n\n1,880\n\n1,986\n\n1,966\n\n1,725\n\n2,459\n\n2,127\n\n3,085\n\n1,816\n\n1,880\n\n2,096\n\n2,740\n\n2,046\n\n2,183\n\n2,051\n\n1,711\n\n1,789\n\n2,363\n\n2,048\n\nJanuary\n\n3,259\n\n1,446\n\n3\n\n4,708\n\n3,167\n\n21,066\n\n20,707\n\n22,313\n\n24,239\n\n25,134\n\n24,501\n\n26,587\n\n25,107\n\n25,808\n\n2010\n\n3,019\n\n2,083\n\n1,730\n\n1,906\n\n2,230\n\n1,888\n\n1,814\n\n1,848\n\n1,756\n\n1,809\n\n2,378\n\n2,040\n\n2011\n\n3,185\n\n1,985\n\n1,947\n\n2,152\n\n2,588\n\n1,913\n\n1,998\n\n1,889\n\n2,063\n\n2,164\n\n2,354\n\n2,349\n\n2012\n\n3,018\n\n1,913\n\n1,927\n\n1,847\n\n2,486\n\n1,836\n\n1,880\n\n1,986\n\n1,966\n\n1,725\n\n2,459\n\n2,127\n\n2013\n\n3,085\n\n1,816\n\n1,880\n\n2,096\n\n2,740\n\n2,046\n\n2,183\n\n2,051\n\n1,711\n\n1,789\n\n2,363\n\n2,048\n\n2014\n\n3,167\n\n63,503\n\n11,840\n\n66,975\n\n10,809\n\n943\n\n868\n\n76,286\n\n60,276\n\n11,871\n\n1,393\n\n73,540\n\n78,652\n\n68,637\n\n13,049\n\n582\n\n82,268\n\n65,657\n\n8,790\n\n1,140\n\n75,587\n\n71,325\n\n10,461\n\n74,701\n\n14,599\n\n1,828\n\n91,128\n\n76,704\n\n14,602\n\n70,845\n\n71,582\n\n27,641\n\n16,265\n\n1,317\n\n1,659\n\n99,803\n\n70,949\n\n27,150\n\n89,506\n\n72,533\n\n16,244\n\n72,592\n\n20,519\n\n1,849\n\n94,960\n\n73,589\n\n20,550\n\n72,627\n\n73,996\n\n7,957\n\n9,432\n\n1,816\n\n2,045\n\n82,400\n\n74,098\n\n85,473\n\n73,938\n\n7,987\n\n9,427\n\n1,630\n\n1,584\n\n1,261\n\n1,830\n\n1,468\n\n1,720\n\n1,769\n\n6,177\n\n4,462\n\n4,864\n\n4,724\n\n5,900\n\n6,589\n\n6,714\n\n6,064\n\n6,332\n\n5,276\n\n5,947\n\n8,533\n\n6,029\n\n4,287\n\n4,424\n\n5,672\n\n6,400\n\n6,236\n\n7,278\n\n6,375\n\n5,624\n\n5,319\n\n5,350\n\n9,598\n\n6,061\n\n4,154\n\n4,556\n\n4,869\n\n5,983\n\n6,728\n\n7,669\n\n6,272\n\n6,122\n\n5,634\n\n6,511\n\n8,068\n\n6,012\n\n4,437\n\n4,677\n\n5,184\n\n6,705\n\n6,739\n\n7,598\n\n6,804\n\n5,779\n\n5,826\n\n5,758\n\n8,477\n\n646\n\n-\n\n853\n\n2,802\n\n5,303\n\n-\n\n-\n\n-\n\n5,275\n\n-\n\n1,386\n\n-\n\n-\n\n6,847\n\n1,407\n\n3,038\n\n-\n\n-\n\n2,376\n\n-\n\n-\n\n4,387\n\n-\n\n4\n\n5\n\n5\n\n30\n\n177\n\n275\n\n238\n\n246\n\n188\n\n352\n\n126\n\n13\n\n2\n\n14\n\n16\n\n37\n\n250\n\n242\n\n239\n\n419\n\n242\n\n257\n\n112\n\n6,827\n\n4,467\n\n5,722\n\n7,556\n\n11,380\n\n6,864\n\n6,952\n\n6,310\n\n11,795\n\n5,628\n\n7,459\n\n8,546\n\n6,031\n\n11,148\n\n5,847\n\n8,747\n\n6,650\n\n6,478\n\n9,893\n\n6,794\n\n5,866\n\n9,963\n\n5,462\n\n2,464\n\n19\n\n12,081\n\n-\n\n1,220\n\n865\n\n3,063\n\n-\n\n-\n\n-\n\n-\n\n-\n\n1,817\n\n618\n\n374\n\n922\n\n1,310\n\n626\n\n3,205\n\n-\n\n700\n\n-\n\n-\n\n1,954\n\n-\n\n715\n\n-\n\n-\n\n4\n\n15\n\n44\n\n302\n\n182\n\n235\n\n254\n\n351\n\n315\n\n86\n\n28\n\n9\n\n2\n\n11\n\n50\n\n328\n\n182\n\n282\n\n305\n\n339\n\n403\n\n121\n\n13\n\n6,061\n\n5,378\n\n5,436\n\n7,976\n\n6,285\n\n6,910\n\n7,904\n\n6,526\n\n6,473\n\n7,766\n\n7,215\n\n8,470\n\n6,943\n\n5,749\n\n5,314\n\n8,439\n\n7,033\n\n7,621\n\n7,880\n\n7,109\n\n8,072\n\n6,229\n\n6,594\n\n8,490\n\n7,822\n\n5,096\n\n4,993\n\n5,101\n\n4,929\n\n5,173\n\n7,428\n\n6,342\n\n6,379\n\n6,107\n\n5,990\n\n7,173\n\n7,755\n\n6,031\n\n4,526\n\n5,367\n\n5,565\n\n5,240\n\n7,415\n\n7,266\n\n6,315\n\n5,927\n\n5,252\n\n6,930\n\n8,296\n\n5,637\n\n4,866\n\n5,044\n\n5,310\n\n4,764\n\n7,677\n\n6,966\n\n5,939\n\n6,566\n\n5,914\n\n7,119\n\n7,440\n\n6,077\n\n5,035\n\n5,100\n\n5,815\n\n5,411\n\n7,747\n\n7,227\n\n5,579\n\n6,111\n\n5,165\n\n7,231\n\n642\n\n-\n\n850\n\n2,806\n\n5,302\n\n-\n\n-\n\n-\n\n5,253\n\n-\n\n1,391\n\n-\n\n-\n\n6,859\n\n1,411\n\n3,045\n\n-\n\n-\n\n2,378\n\n-\n\n4,391\n\n-\n\n-\n\n2,466\n\n-\n\n1,365\n\n816\n\n2,999\n\n-\n\n-\n\n-\n\n-\n\n-\n\n1,815\n\n618\n\n374\n\n922\n\n1,310\n\n626\n\n3,204\n\n-\n\n700\n\n-\n\n-\n\n1,950\n\n-\n\n715\n\n-\n\n-\n\n1\n\n7\n\n34\n\n107\n\n344\n\n386\n\n231\n\n165\n\n403\n\n130\n\n22\n\n-\n\n5\n\n18\n\n15\n\n89\n\n194\n\n232\n\n199\n\n281\n\n280\n\n135\n\n20\n\n-\n\n3\n\n10\n\n46\n\n83\n\n249\n\n194\n\n269\n\n313\n\n334\n\n193\n\n26\n\n8\n\n-\n\n10\n\n14\n\n132\n\n193\n\n220\n\n267\n\n291\n\n384\n\n232\n\n18\n\n83,416\n\n92,890\n\n99,360\n\n90,607\n\n95,607\n\n83,805\n\n85,134\n\n8,464\n\n5,097\n\n5,850\n\n7,941\n\n10,338\n\n5,517\n\n7,814\n\n6,573\n\n11,797\n\n6,510\n\n7,511\n\n7,195\n\n7,755\n\n12,895\n\n5,955\n\n8,427\n\n5,654\n\n5,434\n\n10,025\n\n7,465\n\n10,987\n\n6,207\n\n5,387\n\n9,416\n\n8,296\n\n7,005\n\n5,692\n\n8,089\n\n5,393\n\n5,013\n\n7,871\n\n7,235\n\n6,252\n\n8,715\n\n6,725\n\n7,519\n\n8,370\n\n7,387\n\n5,671\n\n8,318\n\n5,947\n\n6,304\n\n7,967\n\n7,494\n\n7,820\n\n6,495\n\n6,112\n\n7,249\n\n2,746\n\n(3,616)\n\n(7,829)\n\n(1,762)\n\n443\n\n(1,101)\n\n(647)\n\n(1,405)\n\n339\n\n(1,637)\n\n(630)\n\n(128)\n\n(385)\n\n1,042\n\n1,347\n\n(862)\n\n(263)\n\n(2)\n\n(882)\n\n(52)\n\n1,351\n\n(1,724)\n\n(1,747)\n\n(108)\n\n320\n\n996\n\n1,044\n\n(132)\n\n(671)\n\n(5,121)\n\n3,756\n\n75\n\n2,665\n\n(2,235)\n\n(1,627)\n\n(256)\n\n(113)\n\n892\n\n1,897\n\n33\n\n(709)\n\n221\n\n(949)\n\n490\n\n951\n\n(1,427)\n\n(1,638)\n\n(357)\n\n121\n\n1,086\n\n1,317\n\n(87)\n\n(385)\n\n252\n\n(266)\n\n482\n\n1,241\n\n6,426\n\n1,446\n\n3\n\n7,875\n\n8,028\n\n1,444\n\n-\n\n9,472\n\n(1,597)\n\nIssued by:  Statistics Department, P.O. Box 149, Nuku’alofa, Kingdom of Tonga.     Telephone: (676) 23-300/23-913 Fax: (676)24 303\n\nwww.spc.int/prism/tonga/\n\nPage 4\n\n\x0cTable 2.  Total Arrivals by Age, Type of Passangers and Gender January,  2014\n\nAge Group\n\nTotal\n\nTotal\n\nMale\n\nFemale\n\nTotal\n\nVisitors\n\nMale\n\nReturning Residents\n\nFemale\n\nTotal\n\nMale\n\nFemale\n\nType of Passangers\n\n0-4\n\n5-9\n\n10-14\n\n15-19\n\n20-24\n\n25-29\n\n30-34\n\n35-39\n\n40-44\n\n45-49\n\n50-54\n\n55-59\n\n60-64\n\n65-69\n\n70-74\n\n75+\n\nTotal\n\n% Distribution\n\n346\n\n389\n\n532\n\n599\n\n446\n\n531\n\n537\n\n443\n\n543\n\n544\n\n399\n\n356\n\n278\n\n254\n\n106\n\n123\n\n177\n\n206\n\n270\n\n271\n\n185\n\n226\n\n258\n\n244\n\n286\n\n283\n\n217\n\n195\n\n159\n\n124\n\n50\n\n67\n\n169\n\n183\n\n262\n\n328\n\n261\n\n305\n\n279\n\n199\n\n257\n\n261\n\n182\n\n161\n\n119\n\n130\n\n56\n\n56\n\n180\n\n163\n\n226\n\n241\n\n224\n\n275\n\n262\n\n212\n\n308\n\n337\n\n225\n\n208\n\n150\n\n145\n\n58\n\n45\n\n90\n\n95\n\n114\n\n114\n\n86\n\n125\n\n137\n\n128\n\n164\n\n188\n\n125\n\n122\n\n95\n\n78\n\n34\n\n25\n\n90\n\n68\n\n112\n\n127\n\n138\n\n150\n\n125\n\n84\n\n144\n\n149\n\n100\n\n86\n\n55\n\n67\n\n24\n\n20\n\n166\n\n226\n\n306\n\n358\n\n222\n\n256\n\n275\n\n231\n\n235\n\n207\n\n174\n\n148\n\n128\n\n109\n\n48\n\n78\n\n87\n\n111\n\n156\n\n157\n\n99\n\n101\n\n121\n\n116\n\n122\n\n95\n\n92\n\n73\n\n64\n\n46\n\n16\n\n42\n\n79\n\n115\n\n150\n\n201\n\n123\n\n155\n\n154\n\n115\n\n113\n\n112\n\n82\n\n75\n\n64\n\n63\n\n32\n\n36\n\n6,426\n\n100.0\n\n3,218\n\n3,208\n\n3,259\n\n1,720\n\n1,539\n\n3,167\n\n1,498\n\n1,669\n\n50.1\n\n49.9\n\n50.7\n\n26.8\n\n23.9\n\n49.3\n\n23.3\n\n26.0\n\nTable 3.  Total Visitors by Usual Residence and Purpose of Visit January, 2014\n\nCountry of\n\nPurpose of Visit\n\nUsual Residence\n\nTotal\n\n%\n\nHoliday/\n\nBusiness/\n\nVisiting Relative/ Other\n\nNot\n\nDistribution\n\nVacation\n\nConference Friends\n\nReasons\n\nStated\n\nAustralia\n\nNew Zealand\n\nFiji\n\nAmerican Samoa\n\nWestern Samoa\n\nOther Pacific Islands\n\nJapan\n\nChina\n\nIndia\n\nKorea\n\nOther Asian Countries\n\nUK\n\nGermany\n\nFrance\n\nItaly\n\nOther European Countries\n\nAll African Countries\n\nUnited States of America\n\nCanada\n\nOther American Countries\n\nTotal\n\n%  Distribution\n\n713\n\n1,720\n\n144\n\n1\n\n23\n\n37\n\n55\n\n59\n\n3\n\n6\n\n36\n\n48\n\n65\n\n23\n\n4\n\n55\n\n2\n\n240\n\n14\n\n11\n\n3,259\n\n100.0\n\n21.9\n\n52.8\n\n4.4\n\n0.0\n\n0.7\n\n1.1\n\n1.7\n\n1.8\n\n0.1\n\n0.2\n\n1.1\n\n1.5\n\n2.0\n\n0.7\n\n0.1\n\n1.7\n\n0.1\n\n7.4\n\n0.4\n\n0.3\n\n100\n\n233\n\n424\n\n28\n\n4\n\n1\n\n11\n\n28\n\n1\n\n2\n\n8\n\n29\n\n57\n\n11\n\n4\n\n53\n\n1\n\n61\n\n6\n\n7\n\n969\n\n29.7\n\n47\n\n104\n\n54\n\n0\n\n6\n\n8\n\n21\n\n9\n\n1\n\n6\n\n5\n\n9\n\n18\n\n-\n\n-\n\n-\n\n-\n\n-\n\n-\n\n1\n\n289\n\n8.9\n\n314\n\n979\n\n33\n\n1\n\n10\n\n13\n\n14\n\n14\n\n1\n\n11\n\n5\n\n8\n\n1\n\n1\n\n1\n\n111\n\n4\n\n1\n\n1,522\n\n46.7\n\n91\n\n150\n\n21\n\n0\n\n3\n\n14\n\n9\n\n2\n\n4\n\n8\n\n7\n\n2\n\n1\n\n34\n\n4\n\n-\n\n-\n\n-\n\n-\n\n-\n\n350\n\n10.7\n\nIssued by:  Statistics Department, 